#!/bin/bash

mkdir build && cd build

export PKG_CONFIG_PATH="$BUILD_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"

export CLANGINCLUDE_GRAPH_GIT_TOPLEVEL_DIR=${SRC_DIR}

cmake -DCMAKE_BUILD_TYPE=Release \
	  -DGIT_VERSION=${GIT_VERSION} \
	  -DCODE_COVERAGE=OFF \
	  -DWITH_TESTS=ON \
	  -DLLVM_CONFIG_PATH=${BUILD_PREFIX}/bin/llvm-config \
	  -DCONDA_BUILD_PREFIX=${BUILD_PREFIX} \
	  -DCMAKE_INSTALL_PREFIX=${PREFIX} \
	  -DBOOST_STATIC=OFF \
	  -DCMAKE_VERBOSE_MAKEFILE=ON \
	  ..

CTEST_OUTPUT_ON_FAILURE=1 make -j${CPU_COUNT}

CTEST_OUTPUT_ON_FAILURE=1 ctest -j${CPU_COUNT}

make install